### ISSUE TITLE
Error on adding package

### ISSUE THREAD

**Issue by nloui** [copleykj/socialize-linkable-model#1]
Hi there! I'm getting this error when adding any of the socialize modules:

W20160601-20:23:39.687(-7)? (STDERR) ReferenceError: SimpleSchema is not defined

W20160601-20:23:39.687(-7)? (STDERR)     at Package (packages/socialize_linkable-model/common/linkable-model.js:45:1)

W20160601-20:23:39.687(-7)? (STDERR)     at packages/socialize_linkable-model/common/linkable-model.js:55:1

W20160601-20:23:39.688(-7)? (STDERR)     at packages/socialize_linkable-model/common/linkable-model.js:55:1

simpleschema is installed

**Comment by copleykj** [comment]
I'm assuming you resolved this? Would be great if you could post your solution here in case this issue crops up for anyone else.

**Comment by nloui** [comment]
Sure! I just had to run a meteor update (and then meteor update again for the remaining dependencies).  PS - it would be great if there was a version that was compatible with collection2

**Comment by copleykj** [comment]
Collection2 is a requirement actually due to the base-model dependency.

**Comment by nloui** [comment]
Hmm ok good to know. I was having issues implementing because of base model errors and extend.  I assumed it was a conflict, will take a look.

**Comment by jdddog** [comment]
This happened to me after running `meteor add socialize:likeable`. Running a `meteor update` fixed it.

This is what meteor update added / updated:

```
This project is already at Meteor 1.3.4.1, the latest release.

Changes to your project's package version selections from updating package versions:

aldeed:collection2        added, version 2.9.1
aldeed:collection2-core   added, version 1.1.1
aldeed:schema-deny        added, version 1.0.1
aldeed:schema-index       added, version 1.0.1
socialize:base-model      added, version 0.4.0
socialize:linkable-model  upgraded from 0.4.0 to 0.4.1
socialize:server-time     added, version 0.1.2
```
